### ISSUE TITLE
Game crashes when going up the stairs in borg's house in world 3.5

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#168]
Tried to remove non-added stepper
Added the same object twice: tower/reverse_transition.tmx/hero
Trying to run a running scene: "teleport('world3.5/gate.tmx..."
Tried to remove permanent member!
Added the same object twice: world3.5/fortress_b1.tmx/hero
Added the same object twice: world3.5/fortress_f1.tmx/hero
Added the same object twice: world3.5/overworld.tmx/hero
Added the same object twice: world3.5/fortress_f1.tmx/hero
Added the same object twice: world3.5/hometown_interior.tmx/hero
Added the same object twice: world3.5/hometown.tmx/hero
Added the same object twice: world3.5/hometown_interior.tmx/hero
Added the same object twice: world3.5/hometown.tmx/hero
Unhandled MGN exception
com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: res/maps/world3.5/parish_interior.tmx
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:542)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:369)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:390)
	at net.wombatrpgs.mgne.core.MAssets.loadAssets(MAssets.java:76)
	at net.wombatrpgs.mgne.core.MAssets.loadAsset(MAssets.java:96)
	at net.wombatrpgs.mgne.maps.LevelManager.getLevel(LevelManager.java:128)
	at net.wombatrpgs.mgne.maps.LevelManager.getLevel(LevelManager.java:100)
	at net.wombatrpgs.mgne.scenes.commands.SceneTeleport$1.internalRun(SceneTeleport.java:50)
	at net.wombatrpgs.mgne.scenes.SceneCommand.run(SceneCommand.java:95)
	at net.wombatrpgs.mgne.scenes.SceneParser.nextCommand(SceneParser.java:227)
	at net.wombatrpgs.mgne.scenes.SceneParser.run(SceneParser.java:157)
	at net.wombatrpgs.mgne.maps.events.MapEvent.runScene(MapEvent.java:568)
	at net.wombatrpgs.mgne.maps.events.MapEvent$2.onFinish(MapEvent.java:394)
	at net.wombatrpgs.mgne.maps.MapMovable.update(MapMovable.java:177)
	at net.wombatrpgs.mgne.maps.events.MapEvent.update(MapEvent.java:240)
	at net.wombatrpgs.mgne.maps.events.Avatar.update(Avatar.java:118)
	at net.wombatrpgs.mgne.maps.Level.update(Level.java:143)
	at net.wombatrpgs.saga.screen.ScreenWorld.update(ScreenWorld.java:55)
	at net.wombatrpgs.mgne.screen.ScreenStack.update(ScreenStack.java:163)
	at net.wombatrpgs.mgne.screen.ScreenStack.render(ScreenStack.java:146)
	at net.wombatrpgs.mgne.core.SuperGame.render(SuperGame.java:54)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:206)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: res/maps/world3.5/parish_interior.tmx
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:119)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:89)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:479)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:367)
	... 21 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.SerializationException: Error parsing file: res/maps/world3.5/parish_interior.tmx
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:117)
	... 24 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing file: res/maps/world3.5/parish_interior.tmx
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:83)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.getDependencies(TmxMapLoader.java:162)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.getDependencies(TmxMapLoader.java:58)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:64)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: res\maps\world3.5\parish_interior.tmx (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:164)
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:81)
	... 9 more

Thats the error transcript

**Comment by psywombats** [comment]
Well that's weird as shit

**Comment by psywombats** [comment]
Or not, fixed it.
