### ISSUE TITLE
Scrolling on a 3 monster group encounter is fucky

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#185]
If there are three monster groups, with the rightmost one being dead, and you scroll left from the leftmost one, the game crashes.

Here's my error.log:

Unhandled MGN exception
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.wombatrpgs.saga.rpg.battle.Battle.isEnemyAlive(Battle.java:458)
	at net.wombatrpgs.saga.screen.ScreenBattle.selectedCheck(ScreenBattle.java:1188)
	at net.wombatrpgs.saga.screen.ScreenBattle.moveCursor(ScreenBattle.java:1154)
	at net.wombatrpgs.saga.screen.ScreenBattle$5.onCommand(ScreenBattle.java:274)
	at net.wombatrpgs.mgne.screen.Screen.onCommand(Screen.java:365)
	at net.wombatrpgs.saga.screen.SagaScreen.onCommand(SagaScreen.java:137)
	at net.wombatrpgs.saga.screen.ScreenBattle.onCommand(ScreenBattle.java:633)
	at net.wombatrpgs.mgne.screen.Screen.onEvent(Screen.java:221)
	at net.wombatrpgs.saga.screen.SagaScreen.onEvent(SagaScreen.java:126)
	at net.wombatrpgs.mgne.screen.ScreenStack.onEvent(ScreenStack.java:113)
	at net.wombatrpgs.mgne.io.Keymap.signal(Keymap.java:476)
	at net.wombatrpgs.mgne.io.Keymap.update(Keymap.java:121)
	at net.wombatrpgs.mgne.screen.ScreenStack.update(ScreenStack.java:160)
	at net.wombatrpgs.mgne.screen.ScreenStack.render(ScreenStack.java:146)
	at net.wombatrpgs.mgne.core.SuperGame.render(SuperGame.java:54)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by psywombats** [comment]
Fixed.
