### ISSUE TITLE
game breaks when you walk into Elan weapon store

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#202]
Unhandled MGN exception
java.lang.ClassCastException: net.wombatrpgs.sagaschema.rpg.abil.CollectableMDO cannot be cast to net.wombatrpgs.sagaschema.rpg.abil.CombatItemMDO
	at net.wombatrpgs.saga.maps.EventChest.<init>(EventChest.java:60)
	at net.wombatrpgs.saga.maps.SagaEventFactory.createEvent(SagaEventFactory.java:49)
	at net.wombatrpgs.mgne.maps.events.EventFactory.createAndPlace(EventFactory.java:26)
	at net.wombatrpgs.mgne.maps.LoadedLevel.processMap(LoadedLevel.java:162)
	at net.wombatrpgs.mgne.maps.LoadedLevel.postProcessing(LoadedLevel.java:92)
	at net.wombatrpgs.mgne.core.MAssets.loadAssets(MAssets.java:78)
	at net.wombatrpgs.mgne.core.MAssets.loadAsset(MAssets.java:96)
	at net.wombatrpgs.mgne.maps.LevelManager.getLevel(LevelManager.java:135)
	at net.wombatrpgs.mgne.maps.LevelManager.getLevel(LevelManager.java:100)
	at net.wombatrpgs.mgne.scenes.commands.SceneTargetTele$1.internalRun(SceneTargetTele.java:47)
	at net.wombatrpgs.mgne.scenes.SceneCommand.run(SceneCommand.java:95)
	at net.wombatrpgs.mgne.scenes.SceneParser.nextCommand(SceneParser.java:227)
	at net.wombatrpgs.mgne.scenes.SceneParser.run(SceneParser.java:157)
	at net.wombatrpgs.mgne.maps.events.MapEvent.runScene(MapEvent.java:582)
	at net.wombatrpgs.mgne.maps.events.MapEvent$2.onFinish(MapEvent.java:408)
	at net.wombatrpgs.mgne.maps.MapMovable.update(MapMovable.java:177)
	at net.wombatrpgs.mgne.maps.events.MapEvent.update(MapEvent.java:255)
	at net.wombatrpgs.mgne.maps.events.Avatar.update(Avatar.java:128)
	at net.wombatrpgs.mgne.maps.Level.update(Level.java:143)
	at net.wombatrpgs.saga.screen.ScreenWorld.update(ScreenWorld.java:57)
	at net.wombatrpgs.mgne.screen.ScreenStack.update(ScreenStack.java:164)
	at net.wombatrpgs.mgne.screen.ScreenStack.render(ScreenStack.java:147)
	at net.wombatrpgs.mgne.core.SuperGame.render(SuperGame.java:54)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by crumley467** [comment]
The same is true for the item store

**Comment by crumley467** [comment]
And predictably, the Inn

**Comment by crumley467** [comment]
But strangely, the areas below the city are fine!

**Comment by psywombats** [comment]
Was due to excaliber changes
